upload-doc = true
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"}
]


# Header of next release in CHANGELOG.md:
#   ## [Unreleased] - ReleaseDate
